tables:
citadintn.tbltransactionmsg_org_fcout:
number: 1
jdbc_conn_id: jdbc-oracle-citad
table: citadintn.tbltransactionmsg_org_fcout
metastore_table: citad.tbltransactionmsg_org_fcout
save_mode: 'overwrite'
save_format: 'orc'
repartition_num: '1'
query: |
SELECT
MSG_KEY,
MSG_TYPE,
TRX_TYPE,
ERR_STATUS,
SD_TIME,
O_CI_ID,
RESPONSE_CODE,
SERIAL_NO,
TRX_DATE,
INPUT_TYPE,
TAD_ID,
E_SIGN,
R_CI_ID,
O_INDIRECT_ID,
R_INDIRECT_ID,
BALANCE_TIME,
CURRENCY,
AMOUNT,
SD_NAME,
SD_ADDR,
SD_ACCNT,
RV_NAME,
RV_ADDR,
RV_ACCNT,
CONTENT,
OPERT1,
OPERT2,
TRX_STATUS,
TRX_FILE_NAME,
FILE_CORE,
RELATION_NO,
MAC,
PROCESS,
SD_IDENTIFY,
RV_IDENTIFY,
AUTHORIZED,
FEE_CI_ID,
FEE_FLAG,
REFERENCE,
TAX_CODE,
SD_CODE,
RV_CODE,
EX_E_SIGN,
MSG_REASON,
ORIG_ID,
CONFIRM_ID,
APPR_ID,
CREATE_TIME,
APPR_TIME,
GTW_FLAG,
APPR_IN_TIME,
APPR_IN_ID,
CONTENT_EX,
ERR_MSG,
SD_ID_NO,
SD_ISSUE_DATE,
SD_ISSUER,
RV_ID_NO,
RV_ISSUE_DATE,
RV_ISSUER,
OPTION1,
OPTION2,
OPTION3,
SPARE,
CUS_TYPE,
EXCHANGE_RATE,
ACC_NUM,
CHANNEL,
STATUS,
INSERT_TIME,
STANDARD_TIME,
SIGN_TIME,
TRANSFER_TIME,
EXP_MSG,
CLIENT_IP,
MSG_ID,
ROUTING_ID,
IS_SBCO,
TRX_TYPE_ORG,
'{{ cob_dt }}' COB_DT
FROM
CITADINTN.TBLTRANSACTIONMSG_ORG_FCOUT
WHERE
trunc(to_date(CREATE_TIME, 'YYYYMMDDHH24MISS')) = to_date('{{ cob_dt }}', 'YYYY-MM-DD')

citadintn.tbltransactionmsg_org_fcin:
number: 2
jdbc_conn_id: jdbc-oracle-citad
table: citadintn.tbltransactionmsg_org_fcin
metastore_table: citad.tbltransactionmsg_org_fcin
save_mode: 'overwrite'
save_format: 'orc'
repartition_num: '1'
query: |
SELECT
MSG_KEY,
MSG_TYPE,
TRX_TYPE,
ERR_STATUS,
SD_TIME,
O_CI_ID,
RESPONSE_CODE,
SERIAL_NO,
TRX_DATE,
INPUT_TYPE,
TAD_ID,
E_SIGN,
R_CI_ID,
O_INDIRECT_ID,
R_INDIRECT_ID,
BALANCE_TIME,
CURRENCY,
AMOUNT,
SD_NAME,
SD_ADDR,
SD_ACCNT,
RV_NAME,
RV_ADDR,
RV_ACCNT,
CONTENT,
OPERT1,
OPERT2,
TRX_STATUS,
TRX_FILE_NAME,
FILE_CORE,
RELATION_NO,
MAC,
PROCESS,
SD_IDENTIFY,
RV_IDENTIFY,
AUTHORIZED,
FEE_CI_ID,
FEE_FLAG,
REFERENCE,
TAX_CODE,
SD_CODE,
RV_CODE,
EX_E_SIGN,
MSG_REASON,
ORIG_ID,
CONFIRM_ID,
APPR_ID,
CREATE_TIME,
APPR_TIME,
GTW_FLAG,
APPR_IN_TIME,
APPR_IN_ID,
CONTENT_EX,
ERR_MSG,
SD_ID_NO,
SD_ISSUE_DATE,
SD_ISSUER,
RV_ID_NO,
RV_ISSUE_DATE,
RV_ISSUER,
OPTION1,
OPTION2,
OPTION3,
SPARE,
CUS_TYPE,
EXCHANGE_RATE,
ACC_NUM,
INSERT_TIME,
PROCESS_TIME,
UPDATE_TIME,
CLIENT_IP,
STATUS,
TRX_DATE_ORG,
O_CI_ID_ORG,
SERIAL_NO_ORG,
CHANGE_TIME,
CHANGE_CLIENT_IP,
CHANGE_APPR_ID,
'{{ cob_dt }}' COB_DT
FROM
CITADINTN.TBLTRANSACTIONMSG_ORG_FCIN
WHERE
trunc(to_date(CREATE_TIME, 'YYYYMMDDHH24MISS')) = to_date('{{ cob_dt }}', 'YYYY-MM-DD')

citadintn.tbltransactionmsg_org_in:
number: 3
jdbc_conn_id: jdbc-oracle-citad
table: citadintn.tbltransactionmsg_org_in
metastore_table: citad.tbltransactionmsg_org_in
save_mode: 'overwrite'
save_format: 'orc'
repartition_num: '1'
query: |
SELECT
MSG_KEY,
MSG_TYPE,
TRX_TYPE,
ERR_STATUS,
SD_TIME,
O_CI_ID,
RESPONSE_CODE,
SERIAL_NO,
TRX_DATE,
INPUT_TYPE,
TAD_ID,
E_SIGN,
R_CI_ID,
O_INDIRECT_ID,
R_INDIRECT_ID,
BALANCE_TIME,
CURRENCY,
AMOUNT,
SD_NAME,
SD_ADDR,
SD_ACCNT,
RV_NAME,
RV_ADDR,
RV_ACCNT,
CONTENT,
OPERT1,
OPERT2,
TRX_STATUS,
TRX_FILE_NAME,
FILE_CORE,
RELATION_NO,
MAC,
PROCESS,
SD_IDENTIFY,
RV_IDENTIFY,
AUTHORIZED,
FEE_CI_ID,
FEE_FLAG,
REFERENCE,
TAX_CODE,
SD_CODE,
RV_CODE,
EX_E_SIGN,
MSG_REASON,
ORIG_ID,
CONFIRM_ID,
APPR_ID,
CREATE_TIME,
APPR_TIME,
GTW_FLAG,
APPR_IN_TIME,
APPR_IN_ID,
CONTENT_EX,
ERR_MSG,
SD_ID_NO,
SD_ISSUE_DATE,
SD_ISSUER,
RV_ID_NO,
RV_ISSUE_DATE,
RV_ISSUER,
OPTION1,
OPTION2,
OPTION3,
SPARE,
CUS_TYPE,
EXCHANGE_RATE,
ACC_NUM,
INSERT_TIME,
PROCESS_TIME,
UPDATE_TIME,
CLIENT_IP,
STATUS,
TRX_DATE_ORG,
O_CI_ID_ORG,
SERIAL_NO_ORG,
CHANGE_TIME,
CHANGE_CLIENT_IP,
CHANGE_APPR_ID,
'{{ cob_dt }}' COB_DT
FROM
CITADINTN.TBLTRANSACTIONMSG_ORG_IN
WHERE
trunc(to_date(CREATE_TIME, 'YYYYMMDDHH24MISS')) = to_date('{{ cob_dt }}', 'YYYY-MM-DD')

citadintn.tbltransactionmsg_org_out:
number: 4
jdbc_conn_id: jdbc-oracle-citad
table: citadintn.tbltransactionmsg_org_out
metastore_table: citad.tbltransactionmsg_org_out
save_mode: 'overwrite'
save_format: 'orc'
repartition_num: '1'
query: |
SELECT
MSG_KEY,
MSG_TYPE,
TRX_TYPE,
ERR_STATUS,
SD_TIME,
O_CI_ID,
RESPONSE_CODE,
SERIAL_NO,
TRX_DATE,
INPUT_TYPE,
TAD_ID,
E_SIGN,
R_CI_ID,
O_INDIRECT_ID,
R_INDIRECT_ID,
BALANCE_TIME,
CURRENCY,
AMOUNT,
SD_NAME,
SD_ADDR,
SD_ACCNT,
RV_NAME,
RV_ADDR,
RV_ACCNT,
CONTENT,
OPERT1,
OPERT2,
TRX_STATUS,
TRX_FILE_NAME,
FILE_CORE,
RELATION_NO,
MAC,
PROCESS,
SD_IDENTIFY,
RV_IDENTIFY,
AUTHORIZED,
FEE_CI_ID,
FEE_FLAG,
REFERENCE,
TAX_CODE,
SD_CODE,
RV_CODE,
EX_E_SIGN,
MSG_REASON,
ORIG_ID,
CONFIRM_ID,
APPR_ID,
CREATE_TIME,
APPR_TIME,
GTW_FLAG,
APPR_IN_TIME,
APPR_IN_ID,
CONTENT_EX,
ERR_MSG,
SD_ID_NO,
SD_ISSUE_DATE,
SD_ISSUER,
RV_ID_NO,
RV_ISSUE_DATE,
RV_ISSUER,
OPTION1,
OPTION2,
OPTION3,
SPARE,
CUS_TYPE,
EXCHANGE_RATE,
ACC_NUM,
CHANNEL,
STATUS,
INSERT_TIME,
STANDARD_TIME,
SIGN_TIME,
TRANSFER_TIME,
EXP_MSG,
CLIENT_IP,
MSG_ID,
ROUTING_ID,
IS_SBCO,
TRX_TYPE_ORG,
ROUTING_ID_EXT,
'{{ cob_dt }}' COB_DT
FROM
CITADINTN.TBLTRANSACTIONMSG_ORG_OUT
WHERE
trunc(to_date(CREATE_TIME, 'YYYYMMDDHH24MISS')) = to_date('{{ cob_dt }}', 'YYYY-MM-DD')