spark:
  job_name: std_trns_typ_ref
source:
  table: profile.prf_zutbltxntyp
target:
  table: hive.std.trns_typ_ref
  write_hist_table: '0'
  standardized: 0

query:
  init_sql: |
    CREATE TABLE hive.std.trns_typ_ref(
      cob_dt date,
      desc string COMMENT 'Description, Source: ZUTBLTXNTYP.desc',
      limit_check_ind int COMMENT 'Indicator for limit checking, Source: ZUTBLTXNTYP.main',
      transaction_typ int COMMENT 'Transaction Type, Source: ZUTBLTXNTYP.typ',
      change_type string COMMENT 'I/U'
    )
    USING iceberg

  select_sql: |
    SELECT
      to_date(cob_dt,'yyyy-MM-dd') cob_dt,
      desc,
      cast(main as int) limit_check_ind,
      cast(typ as int) transaction_typ
    FROM
    profile.prf_zutbltxntyp
    WHERE
    cob_dt = '{{ cob_dt }}'

columns:
- name: cob_dt
  do_not_compare: 1
- name: desc
  do_not_compare: 1
  primary_key: 1
- name: limit_check_ind
- name: transaction_typ
